# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# For more information about the golangci-lint configuration file, refer to:
# https://golangci-lint.run/usage/configuration/

issues:
  exclude-rules:
    # Exclude staticcheck for some rules.
    - linters: [staticcheck]
      text: "SA1006|SA1019|SA4006|SA4010|SA4017|SA5007|SA6005|SA9004"
    # Exclude line length linter for generated files.
    - linters: [lll]
      source: "^//go:generate "

linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unused

run:
  concurrency: 4
  timeout: 10m
  exclude-files:
    - ".*\\.hcl2spec\\.go$"

output:
  formats:
    - format: colored-line-number

linters-settings:
  errcheck:
    exclude-functions:
      - "fmt:.*"
      - "io:Close"
