// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package supervisor

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatImportImageConfig is an auto-generated flat version of ImportImageConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatImportImageConfig struct {
	ImportSourceURL            *string `mapstructure:"import_source_url" cty:"import_source_url" hcl:"import_source_url"`
	ImportSourceSSLCertificate *string `mapstructure:"import_source_ssl_certificate" cty:"import_source_ssl_certificate" hcl:"import_source_ssl_certificate"`
	ImportTargetLocationName   *string `mapstructure:"import_target_location_name" cty:"import_target_location_name" hcl:"import_target_location_name"`
	ImportTargetImageType      *string `mapstructure:"import_target_image_type" cty:"import_target_image_type" hcl:"import_target_image_type"`
	ImportRequestName          *string `mapstructure:"import_request_name" cty:"import_request_name" hcl:"import_request_name"`
	WatchImportTimeoutSec      *int    `mapstructure:"watch_import_timeout_sec" cty:"watch_import_timeout_sec" hcl:"watch_import_timeout_sec"`
	CleanImportedImage         *bool   `mapstructure:"clean_imported_image" cty:"clean_imported_image" hcl:"clean_imported_image"`
}

// FlatMapstructure returns a new FlatImportImageConfig.
// FlatImportImageConfig is an auto-generated flat version of ImportImageConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*ImportImageConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatImportImageConfig)
}

// HCL2Spec returns the hcl spec of a ImportImageConfig.
// This spec is used by HCL to read the fields of ImportImageConfig.
// The decoded values from this spec will then be applied to a FlatImportImageConfig.
func (*FlatImportImageConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"import_source_url":             &hcldec.AttrSpec{Name: "import_source_url", Type: cty.String, Required: false},
		"import_source_ssl_certificate": &hcldec.AttrSpec{Name: "import_source_ssl_certificate", Type: cty.String, Required: false},
		"import_target_location_name":   &hcldec.AttrSpec{Name: "import_target_location_name", Type: cty.String, Required: false},
		"import_target_image_type":      &hcldec.AttrSpec{Name: "import_target_image_type", Type: cty.String, Required: false},
		"import_request_name":           &hcldec.AttrSpec{Name: "import_request_name", Type: cty.String, Required: false},
		"watch_import_timeout_sec":      &hcldec.AttrSpec{Name: "watch_import_timeout_sec", Type: cty.Number, Required: false},
		"clean_imported_image":          &hcldec.AttrSpec{Name: "clean_imported_image", Type: cty.Bool, Required: false},
	}
	return s
}
