// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package supervisor

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatCreateSourceConfig is an auto-generated flat version of CreateSourceConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatCreateSourceConfig struct {
	ImageName         *string `mapstructure:"image_name" required:"true" cty:"image_name" hcl:"image_name"`
	ClassName         *string `mapstructure:"class_name" required:"true" cty:"class_name" hcl:"class_name"`
	StorageClass      *string `mapstructure:"storage_class" required:"true" cty:"storage_class" hcl:"storage_class"`
	SourceName        *string `mapstructure:"source_name" cty:"source_name" hcl:"source_name"`
	NetworkType       *string `mapstructure:"network_type" cty:"network_type" hcl:"network_type"`
	NetworkName       *string `mapstructure:"network_name" cty:"network_name" hcl:"network_name"`
	KeepInputArtifact *bool   `mapstructure:"keep_input_artifact" cty:"keep_input_artifact" hcl:"keep_input_artifact"`
}

// FlatMapstructure returns a new FlatCreateSourceConfig.
// FlatCreateSourceConfig is an auto-generated flat version of CreateSourceConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*CreateSourceConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatCreateSourceConfig)
}

// HCL2Spec returns the hcl spec of a CreateSourceConfig.
// This spec is used by HCL to read the fields of CreateSourceConfig.
// The decoded values from this spec will then be applied to a FlatCreateSourceConfig.
func (*FlatCreateSourceConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"image_name":          &hcldec.AttrSpec{Name: "image_name", Type: cty.String, Required: false},
		"class_name":          &hcldec.AttrSpec{Name: "class_name", Type: cty.String, Required: false},
		"storage_class":       &hcldec.AttrSpec{Name: "storage_class", Type: cty.String, Required: false},
		"source_name":         &hcldec.AttrSpec{Name: "source_name", Type: cty.String, Required: false},
		"network_type":        &hcldec.AttrSpec{Name: "network_type", Type: cty.String, Required: false},
		"network_name":        &hcldec.AttrSpec{Name: "network_name", Type: cty.String, Required: false},
		"keep_input_artifact": &hcldec.AttrSpec{Name: "keep_input_artifact", Type: cty.Bool, Required: false},
	}
	return s
}
