// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package supervisor

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatPublishSourceConfig is an auto-generated flat version of PublishSourceConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatPublishSourceConfig struct {
	PublishImageName       *string `mapstructure:"publish_image_name" cty:"publish_image_name" hcl:"publish_image_name"`
	WatchPublishTimeoutSec *int    `mapstructure:"watch_publish_timeout_sec" cty:"watch_publish_timeout_sec" hcl:"watch_publish_timeout_sec"`
}

// FlatMapstructure returns a new FlatPublishSourceConfig.
// FlatPublishSourceConfig is an auto-generated flat version of PublishSourceConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*PublishSourceConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatPublishSourceConfig)
}

// HCL2Spec returns the hcl spec of a PublishSourceConfig.
// This spec is used by HCL to read the fields of PublishSourceConfig.
// The decoded values from this spec will then be applied to a FlatPublishSourceConfig.
func (*FlatPublishSourceConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"publish_image_name":        &hcldec.AttrSpec{Name: "publish_image_name", Type: cty.String, Required: false},
		"watch_publish_timeout_sec": &hcldec.AttrSpec{Name: "watch_publish_timeout_sec", Type: cty.Number, Required: false},
	}
	return s
}
