// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package supervisor

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatValidatePublishConfig is an auto-generated flat version of ValidatePublishConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatValidatePublishConfig struct {
	PublishLocationName *string `mapstructure:"publish_location_name" cty:"publish_location_name" hcl:"publish_location_name"`
}

// FlatMapstructure returns a new FlatValidatePublishConfig.
// FlatValidatePublishConfig is an auto-generated flat version of ValidatePublishConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*ValidatePublishConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatValidatePublishConfig)
}

// HCL2Spec returns the hcl spec of a ValidatePublishConfig.
// This spec is used by HCL to read the fields of ValidatePublishConfig.
// The decoded values from this spec will then be applied to a FlatValidatePublishConfig.
func (*FlatValidatePublishConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"publish_location_name": &hcldec.AttrSpec{Name: "publish_location_name", Type: cty.String, Required: false},
	}
	return s
}
