---
name: Documentation
description: Found a typo or something that needs clarification?
labels:
  - documentation
  - needs-review
type: task
projects:
  - vmware/48
body:
  - type: markdown
    attributes:
      value: >
        When filing a documentation issue, please include the following information.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: The Code of Conduct applies to you when interacting with the community here on GitHub and contributing code.
      options:
        - label: I have read and agree to the [Code of Conduct](https://github.com/vmware/packer-plugin-vsphere/blob/main/CODE_OF_CONDUCT.md).
          required: true
        - label: Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue description to help the maintainers prioritize.
          required: false
        - label: Do not leave "+1" or other comments that do not add relevant information or questions.
          required: false
        - label: If you are interested in working on this issue or have submitted a pull request, please leave a comment.
          required: false
  - type: textarea
    id: detail
    attributes:
      label: Detail
      description: What part of the documentation needs to be changed?
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: How should the documentation be changed to address the issue?
    validations:
      required: false
