// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package iso

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatCleanupConfig is an auto-generated flat version of CleanupConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatCleanupConfig struct {
	Destroy *bool `mapstructure:"destroy" cty:"destroy" hcl:"destroy"`
}

// FlatMapstructure returns a new FlatCleanupConfig.
// FlatCleanupConfig is an auto-generated flat version of CleanupConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*CleanupConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatCleanupConfig)
}

// HCL2Spec returns the hcl spec of a CleanupConfig.
// This spec is used by HCL to read the fields of CleanupConfig.
// The decoded values from this spec will then be applied to a FlatCleanupConfig.
func (*FlatCleanupConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"destroy": &hcldec.AttrSpec{Name: "destroy", Type: cty.Bool, Required: false},
	}
	return s
}
